insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211010E7YATEG' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-02 08:49:06' as created_at, '2022-11-02 08:49:06' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1344162);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211021NRMGU6W' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-02 11:00:35' as created_at, '2022-11-02 11:00:35' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1344404);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 22110228R92HFC' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-02 16:07:28' as created_at, '2022-11-02 16:07:28' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1344622);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211034DJ2E83P' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-03 14:03:25' as created_at, '2022-11-03 14:03:25' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1345605);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211058XCBSEED' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-05 09:04:20' as created_at, '2022-11-05 09:04:20' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1346713);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211058KG0CXDQ' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-05 08:46:37' as created_at, '2022-11-05 08:46:37' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1346716);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211059C73HU6Q' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-05 12:29:04' as created_at, '2022-11-05 12:29:04' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1347171);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221107EC2WCQHB' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-07 14:10:09' as created_at, '2022-11-07 14:10:09' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1348763);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221107EV1HQNHA' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-08 08:38:38' as created_at, '2022-11-08 08:38:38' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1349087);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221108J2ASJW14' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-09 09:32:30' as created_at, '2022-11-09 09:32:30' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1349924);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221109KVJ53BB1' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-09 16:09:32' as created_at, '2022-11-09 16:09:32' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1350633);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221109MEHKM7EQ' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-10 09:54:06' as created_at, '2022-11-10 09:54:06' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1350660);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221111QCJXR9Q9' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-11 08:44:54' as created_at, '2022-11-11 08:44:54' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1351693);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221111RQTRR7E5' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-11 16:07:43' as created_at, '2022-11-11 16:07:43' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1353131);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221111RQM33787' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-11 16:07:45' as created_at, '2022-11-11 16:07:45' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1353132);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221111S785VNKA' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-12 09:28:36' as created_at, '2022-11-12 09:28:36' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1353226);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221112TPJA7QJK' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-12 09:55:32' as created_at, '2022-11-12 09:55:32' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1353435);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221112TVH9A6TB' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-12 12:21:02' as created_at, '2022-11-12 12:21:02' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1353457);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221112U2KJBB57' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-13 08:15:20' as created_at, '2022-11-13 08:15:20' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1353531);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211130BXAXCF5' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-13 12:02:20' as created_at, '2022-11-13 12:02:20' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1353689);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211142M5N4083' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-14 11:05:17' as created_at, '2022-11-14 11:05:17' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1353946);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 22111430MC7K9X' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-14 14:17:01' as created_at, '2022-11-14 14:17:01' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1354015);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211143X4DR76Y' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-15 08:57:17' as created_at, '2022-11-15 08:57:17' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1354067);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211143H4BJQJQ' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-15 08:33:34' as created_at, '2022-11-15 08:33:34' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1354107);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211155NVDSK23' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-15 16:02:24' as created_at, '2022-11-15 16:02:24' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1354350);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211168XPJU6KS' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-17 08:38:27' as created_at, '2022-11-17 08:38:27' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1354703);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221118CRB81QV4' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-18 11:04:33' as created_at, '2022-11-18 11:04:33' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1355124);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221119EMS8PJ69' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-19 09:17:42' as created_at, '2022-11-19 09:17:42' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1355216);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221121MBQBU7KV' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-21 11:14:28' as created_at, '2022-11-21 11:14:28' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1355781);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221121MGRN5BD2' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-21 14:20:00' as created_at, '2022-11-21 14:20:00' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1355800);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221122PE1TNVDP' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-22 08:36:24' as created_at, '2022-11-22 08:36:24' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1355871);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221121NGSWDXCP' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-22 08:36:34' as created_at, '2022-11-22 08:36:34' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1355880);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221122R2YUH5AE' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-23 08:35:01' as created_at, '2022-11-23 08:35:01' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1356192);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221123SYFMG21W' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-23 16:25:11' as created_at, '2022-11-23 16:25:11' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1356434);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221124UB5DKUXY' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-24 08:23:56' as created_at, '2022-11-24 08:23:56' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1356447);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221123TMXY12KY' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-24 08:24:06' as created_at, '2022-11-24 08:24:06' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1356455);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221123T7D2GB02' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-24 08:38:11' as created_at, '2022-11-24 08:38:11' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1356670);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211251Q18B411' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-25 14:17:13' as created_at, '2022-11-25 14:17:13' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1357387);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 22112644KE37K9' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-27 08:29:27' as created_at, '2022-11-27 08:29:27' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1357956);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 22112645W1DWBQ' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-27 08:21:29' as created_at, '2022-11-27 08:21:29' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1357986);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 22112649ESJ7HH' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-27 08:22:08' as created_at, '2022-11-27 08:22:08' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1358025);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211276GGH8HH5' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-27 12:07:20' as created_at, '2022-11-27 12:07:20' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1358172);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211276WM7SDWS' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-28 08:20:56' as created_at, '2022-11-28 08:20:56' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1358303);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211289DAR5Y8Y' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-28 16:15:36' as created_at, '2022-11-28 16:15:36' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1358874);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211289D5VRFDY' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-28 16:15:36' as created_at, '2022-11-28 16:15:36' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1358876);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221129B5M5YQ6V' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-29 08:42:46' as created_at, '2022-11-29 08:42:46' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359046);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221128A2KWB60T' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-29 08:43:09' as created_at, '2022-11-29 08:43:09' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359068);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 2211289VRV1PMB' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-29 09:04:16' as created_at, '2022-11-29 09:04:16' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359079);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221129BKVJHM53' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-29 14:03:36' as created_at, '2022-11-29 14:03:36' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359226);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221130DQDWUPJD' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-30 09:04:14' as created_at, '2022-11-30 09:04:14' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359347);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221129CH3209U8' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-30 08:51:19' as created_at, '2022-11-30 08:51:19' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359378);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221130DVXWT96R' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-30 11:18:56' as created_at, '2022-11-30 11:18:56' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359670);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221130E7XM0768' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-30 14:24:29' as created_at, '2022-11-30 14:24:29' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359753);
insert into journal(`coa_id`, `name`, `debet`, `credit`, `description`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `transaction_id`, `transaction_type`, `tags`, `store`, `temp_column`, `type`, `branch_office_id`)
select 3458 as coa_id, 'DO VALIDATE - 221130EAH2VV7Q' as name, 0.01 as debet, null as credit, null as description, 1 as status, 201 as created_by, 201 as updated_by, null, '2022-11-30 16:02:55' as created_at, '2022-11-30 16:02:55' as updated_at, null, id as transaction_id, 'SALES', null, store_name, null, 2, 6
from sales_order where id in (1359761);
